### PR TITLE
Fixed the lib folder contents.

### PR DESCRIPTION
**Pull request by SyedAsadKazmi**
- Installed the dependencies by seeing the [lib](https://github.com/Gearbox-protocol/dev-bots-tutorial/tree/main/lib) folder of the original [dev-bots-tutorial](https://github.com/Gearbox-protocol/dev-bots-tutorial) by using the exact commit hashes:

  ```bash
  forge install 1inch/solidity-utils@8bf9ccb gearbox-protocol/core-v2@e890150 gearbox-protocol/core-v3@ca43d1b gearbox-protocol/integrations-v3@302c635 openzeppelin/openzeppelin-contracts@932fddf --no-commit
  ```

- Created a folder named as `1inch` folder inside `lib`, and moved the `solidity-utils` folder into it.

- Created a folder named as `gearbox-protocol` inside `lib`, and moved the `core-v2`, `core-v3` and `integrations-v3` into it.

### CODE REVIEW

**Comment by Hakob23** [comment]
Receiving this error when calling ```forge intstall``` or ```forge test```
image

**Comment by SyedAsadKazmi** [comment]
Do one thing, just delete the `lib` folder, and follow the exact steps that I've mentioned in my [answer](https://ethereum.stackexchange.com/a/165958/91017) at Eth-StackExchange.

**Comment by SyedAsadKazmi** [comment]
Sorry to bother you. I just want to confirm that you've marked my answer as unaccepted, and mark another answer as accepted. Right?

**Comment by Hakob23** [comment]
That was a mistake. Now your answer is the one accepted

**Pull request merged**
